

-- Version 1
CREATE TABLE IF NOT EXISTS customer (
    CheckExceedCommitmentDate BOOLEAN,
    DueCommitmentsXDay NUMERIC,
    EffectOfTradeAmount NUMERIC,
    GenerateVCS BOOLEAN,
    ThirdLanguage TEXT,
    InvoicingChargesAmount NUMERIC,
    AutomaticStockBooking BOOLEAN,
    CustomerToUseInCustomerProducts NUMERIC,
    ExtendedCurrentAmount NUMERIC,
    ThresholdBeforeExceedAmount NUMERIC,
    Name TEXT,
    UseInvoicingAddressAsDeliveryAddress BOOLEAN,
    UseInvoicingContactAsDeliveryContact BOOLEAN,
    MainDeliveryAddress_Npai BOOLEAN,
    MainInvoicingAddress_Npai BOOLEAN,
    MainDeliveryContact_NaturalPerson BOOLEAN,
    MainDeliveryContact_OptIn BOOLEAN,
    Id TEXT,
    MainInvoicingContact_NaturalPerson BOOLEAN,
    MainInvoicingContact_OptIn BOOLEAN,
    NaturalPerson BOOLEAN,
    TerritorialityId UUID,
    FinancialDiscountType NUMERIC,
    FinancialDiscountRate NUMERIC,
    FinancialDiscountPaymentDelay NUMERIC,
    ActiveState NUMERIC,
    DiscountRate NUMERIC,
    SecondDiscountRate NUMERIC,
    AllowedAmount NUMERIC,
    CurrentAmount NUMERIC,
    InitialAmount NUMERIC,
    ExceedAmount NUMERIC,
    MustRetrieveCommitmentsFromAccounting BOOLEAN,
    PriceWithTaxBased BOOLEAN,
    MustBeReminder BOOLEAN,
    DayNumberToFirstReminder NUMERIC,
    DayNumberToSecondReminder NUMERIC,
    DayNumberToThirdReminder NUMERIC,
    IsCustomerAccount BOOLEAN,
    WebContactSendKind NUMERIC,
    SubjectToRE BOOLEAN,
    UniqueId UUID,
    DisallowOrderAssort BOOLEAN,
    DisallowDeliveryAssort BOOLEAN,
    SendReminderToPayerThird BOOLEAN,
    xx_Envoi_carte_voeux BOOLEAN,
    AssortDeliveryByOrder BOOLEAN,
    CreatePosDeliveryOrderByDefault BOOLEAN,
    LoyaltyOriginReportType NUMERIC,
    LoyaltyOriginReportValue NUMERIC,
    LoyaltyValue NUMERIC,
    LoyaltyCardType TEXT,
    LoyaltyCardId TEXT,
    LoyaltyCardCreationDate TIMESTAMP,
    LoyaltyCardValidityDuration NUMERIC,
    LoyaltyCardExpiryDate TIMESTAMP,
    LoyaltyCardRenewalDate TIMESTAMP,
    sysRecordVersion NUMERIC,
    sysRecordVersionId UUID,
    sysEditCounter NUMERIC,
    SelectedReminderReport TEXT,
    ShippingId TEXT,
    DocumentSerialId TEXT,
    IdentificationType TEXT,
    AnalyticAccounting_GridId TEXT,
    Type NUMERIC,
    Accounts_Account TEXT,
    CurrencyId TEXT,
    Group1 TEXT,
    Group2 TEXT,
    ColleagueId TEXT,
    FirstInvoicingDate TIMESTAMP,
    SettlementModeId TEXT,
    PaymentDate TIMESTAMP,
    PriceListCategoryId TEXT,
    Siren TEXT,
    NAF TEXT,
    FamilyId TEXT,
    SubFamilyId TEXT,
    IntracommunityVATNumber TEXT,
    MainInvoicingContact_ExternalId_GoogleId TEXT,
    MainInvoicingContact_ExternalId_OutlookId TEXT,
    Civility TEXT,
    MainDeliveryContact_ExternalId_GoogleId TEXT,
    MainDeliveryContact_ExternalId_OutlookId TEXT,
    MainInvoicingContact_Civility TEXT,
    MainInvoicingContact_Name TEXT,
    MainInvoicingContact_FirstName TEXT,
    MainInvoicingContact_Phone TEXT,
    MainInvoicingContact_CellPhone TEXT,
    MainInvoicingContact_Fax TEXT,
    MainInvoicingContact_Email TEXT,
    MainInvoicingContact_Function TEXT,
    MainInvoicingContact_Department TEXT,
    MainInvoicingAddress_WebSite TEXT,
    MainInvoicingAddress_Longitude NUMERIC,
    MainInvoicingAddress_Latitude NUMERIC,
    MainDeliveryContact_Civility TEXT,
    MainDeliveryContact_Name TEXT,
    MainDeliveryContact_FirstName TEXT,
    MainDeliveryContact_Phone TEXT,
    MainDeliveryContact_CellPhone TEXT,
    MainDeliveryContact_Fax TEXT,
    MainDeliveryContact_Email TEXT,
    MainDeliveryContact_Function TEXT,
    MainDeliveryContact_Department TEXT,
    MainDeliveryAddress_WebSite TEXT,
    MainDeliveryAddress_Longitude NUMERIC,
    MainDeliveryAddress_Latitude NUMERIC,
    MainInvoicingAddress_Address1 TEXT,
    MainInvoicingAddress_Address2 TEXT,
    MainInvoicingAddress_Address3 TEXT,
    MainInvoicingAddress_Address4 TEXT,
    MainInvoicingAddress_ZipCode TEXT,
    MainInvoicingAddress_City TEXT,
    MainInvoicingAddress_State TEXT,
    MainInvoicingAddress_CountryIsoCode TEXT,
    MainInvoicingAddress_Description TEXT,
    MainInvoicingAddress_Civility TEXT,
    MainInvoicingAddress_ThirdName TEXT,
    MainDeliveryAddress_Address1 TEXT,
    MainDeliveryAddress_Address2 TEXT,
    MainDeliveryAddress_Address3 TEXT,
    MainDeliveryAddress_Address4 TEXT,
    MainDeliveryAddress_ZipCode TEXT,
    MainDeliveryAddress_City TEXT,
    MainDeliveryAddress_State TEXT,
    MainDeliveryAddress_CountryIsoCode TEXT,
    MainDeliveryAddress_Description TEXT,
    MainDeliveryAddress_Civility TEXT,
    MainDeliveryAddress_ThirdName TEXT,
    sysCreatedDate TIMESTAMP,
    sysCreatedUser TEXT,
    sysModifiedDate TIMESTAMP,
    sysModifiedUser TEXT,
    NotesClear TEXT,
    Notes TEXT,
    Accounts_BillOfExchangeAccountingAccount TEXT,
    TaxIds0 TEXT,
    TaxIds1 TEXT,
    TaxIds2 TEXT,
    PaymentThirdId TEXT,
    InvoicingThirdId TEXT,
    InvoicingChargesVatId UUID,
    LastInvoicingDate TIMESTAMP,
    DocumentPrintMention TEXT,
    StorehouseId TEXT,
    Accounts_AuxiliaryAccount TEXT,
    Accounts_DoubtfulAccount TEXT,
    SchedulerColor TEXT,
    TravelExpenseId TEXT,
    Accounts_SecurityBondAccount TEXT,
    Accounts_SecurityBondForGoodCompletedWorkAccount TEXT,
    ShowTechnicalSheetOnFront BOOLEAN,
    TechnicalSheetClear TEXT,
    TechnicalSheet TEXT,
    MainDeliveryContact_AllowUsePersonnalDatas BOOLEAN,
    MainInvoicingContact_AllowUsePersonnalDatas BOOLEAN,
    AllowUsePersonnalDatas BOOLEAN,
    Nic TEXT,
    LoyaltyCumulativeTurnoverReport NUMERIC,
    LoyaltyCumulativeTurnover NUMERIC,
    DepositPercentage NUMERIC,
    SecurityBondRate NUMERIC,
    SecurityBondRateForGoodCompletedWork NUMERIC,
    BuyerReference TEXT,
    GoCardLessThirdId TEXT,
    DefaultBankAccountId TEXT
);

CREATE TABLE IF NOT EXISTS item (
    BarCodePrice NUMERIC,
    BarCodeWeight NUMERIC,
    PosAddItem BOOLEAN,
    LoyaltyPoints NUMERIC,
    CalculateLoyaltyFrom NUMERIC,
    GiftVoucher BOOLEAN,
    IntrastatExcluded BOOLEAN,
    CreateCustomerProductInCustomerPark BOOLEAN,
    IsMaintenanceContract BOOLEAN,
    IsGuaranteeExtension BOOLEAN,
    CustomerParkCreation NUMERIC,
    StockBookingAllowed BOOLEAN,
    AutomaticStockBooking BOOLEAN,
    IncludeToRecursiveReplenishment BOOLEAN,
    IncludeToFabricationReplenishment BOOLEAN,
    IncludeToSupplierReplenishment BOOLEAN,
    CadenceQuantity NUMERIC,
    CadenceNumberOfDays NUMERIC,
    DoNotAssortAssemblyRequestsWithDifferentDates BOOLEAN,
    MaximumGapDayToAssort NUMERIC,
    NomenclatureAccountingTransferTypeForSale NUMERIC,
    NomenclatureAccountingTransferTypeForPurchase NUMERIC,
    VirtualPump NUMERIC,
    VirtualStockValue NUMERIC,
    BookedQuantity NUMERIC,
    PurchaseBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    NotOnMarket BOOLEAN,
    PurchaseUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    CanBePartiallyDelivered BOOLEAN,
    Caption TEXT,
    Oxatis_Oxatis_HandlingSurcharge1ST NUMERIC,
    Oxatis_Oxatis_HandlingSurchargeOthers NUMERIC,
    InterventionDurationEqualsQuantity BOOLEAN,
    Height NUMERIC,
    Width NUMERIC,
    Length NUMERIC,
    Oxatis_Oxatis_UseSubFamilyAsBrand BOOLEAN,
    IsManagedByCounterMark BOOLEAN,
    IsCounterMarkForced BOOLEAN,
    SalePurchaseConversionRate NUMERIC,
    LimitDateMode NUMERIC,
    LimitDateSafetyDelay NUMERIC,
    UniqueId UUID,
    PurchasePrice NUMERIC,
    ChargeRate NUMERIC,
    ChargeAmount NUMERIC,
    CostPrice NUMERIC,
    InterestRate NUMERIC,
    InterestAmount NUMERIC,
    SalePriceVatExcluded NUMERIC,
    BrandRate NUMERIC,
    VatAmount NUMERIC,
    SalePriceVatIncluded NUMERIC,
    ManageStock BOOLEAN,
    RealStock NUMERIC,
    Pump NUMERIC,
    StockValue NUMERIC,
    OrderedQuantity NUMERIC,
    SuppliersOrderedQuantity NUMERIC,
    VirtualStock NUMERIC,
    DefaultQuantity NUMERIC,
    Volume NUMERIC,
    Weight NUMERIC,
    NetWeight NUMERIC,
    ComponentsPurchasePrice NUMERIC,
    ComponentsCostPrice NUMERIC,
    ComponentsSalePriceVatExcluded NUMERIC,
    ComponentsSalePriceVatIncluded NUMERIC,
    PrintComponentDetail NUMERIC,
    AssemblingVirtualQuantity NUMERIC,
    DisassemblingQuantity NUMERIC,
    QuantityUsedToAssemblate NUMERIC,
    QuantityFromDisassembling NUMERIC,
    AllowNegativeStock BOOLEAN,
    UseComponentVat BOOLEAN,
    ApplyPriceListOnComponents BOOLEAN,
    ActiveState NUMERIC,
    AdvisedSalePriceVATExcluded NUMERIC,
    SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    TrackingMode NUMERIC,
    AllowComponentsModification BOOLEAN,
    AllowPublishOnWeb BOOLEAN,
    ImageVersion NUMERIC,
    PriceDecimalNumber NUMERIC,
    IsHumanServicesIncludedInAttestation BOOLEAN,
    Oxatis_Oxatis_ShowInStockNote BOOLEAN,
    Oxatis_Oxatis_ShowStockLevel BOOLEAN,
    Oxatis_Oxatis_ShowIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStockScenario NUMERIC,
    Oxatis_Oxatis_ShowDaysToship BOOLEAN,
    Oxatis_Oxatis_ShipPrice NUMERIC,
    Oxatis_Oxatis_DaysToship NUMERIC,
    Oxatis_Oxatis_UserMainSupplierDaysToship BOOLEAN,
    Id TEXT,
    ItemType NUMERIC,
    BillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    SaleUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    UpdateComponentsStockInFabrication BOOLEAN,
    CustomersDeliveryOrderPreparingQuantity NUMERIC,
    CustomersReturnOrderPreparingQuantity NUMERIC,
    SuppliersDeliveryOrderPreparingQuantity NUMERIC,
    SuppliersReturnOrderPreparingQuantity NUMERIC,
    StockBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    PurchaseChargesRate NUMERIC,
    PosIsScale BOOLEAN,
    PosTare NUMERIC,
    BillOfQuantitiesProgram_Program TEXT,
    ReplenishmentDeliveryAddressType NUMERIC,
    SaleUnitPriceProgram_Program TEXT,
    DesCom TEXT,
    DesComClear TEXT,
    ItemImage TEXT,
    BarCode TEXT,
    UnitId TEXT,
    FamilyId TEXT,
    SubFamilyId TEXT,
    sysCreatedDate TIMESTAMP,
    sysCreatedUser TEXT,
    sysModifiedDate TIMESTAMP,
    sysModifiedUser TEXT,
    NotesClear TEXT,
    Notes TEXT,
    Oxatis_Oxatis_CategoryType1 TEXT,
    Oxatis_Oxatis_CategoryType2 TEXT,
    Oxatis_Oxatis_CategoryType3 TEXT,
    Oxatis_Oxatis_CategoryId1 TEXT,
    Oxatis_Oxatis_CategoryId2 TEXT,
    Oxatis_Oxatis_CategoryId3 TEXT,
    Oxatis_Oxatis_MetaTitle TEXT,
    Oxatis_Oxatis_MetaDescription TEXT,
    Oxatis_Oxatis_MetaKeywords TEXT,
    Oxatis_Oxatis_Brand TEXT,
    MainIntervener TEXT,
    IntrastatNc8NomenclatureId TEXT,
    Group1 TEXT,
    Group2 TEXT,
    NotPrintable TEXT,
    NotIncluded TEXT,
    IsFixedPrice TEXT,
    NonInvoiceableType TEXT,
    ComponentCalculationType TEXT,
    ReplacementItem TEXT,
    WeightUnitId TEXT,
    NumberOfItemByPackage NUMERIC,
    VolumeUnitId TEXT,
    SupplierId TEXT,
    EcotaxId TEXT,
    StockDestination NUMERIC,
    StockVarianceAccount TEXT,
    CurrentStockAccount TEXT,
    VatId UUID,
    sysRecordVersion NUMERIC,
    sysRecordVersionId UUID,
    sysEditCounter NUMERIC,
    LimitDateSafetyDelayMode TEXT,
    DefaultLifeTime TEXT,
    PurchasePriceUpdateType TEXT,
    AnalyticAccounting_GridId TEXT,
    PurchaseUnitId TEXT,
    DimensionUnitId TEXT,
    Oxatis_Oxatis_LongDescription TEXT,
    Oxatis_Oxatis_LongDescriptionClear TEXT,
    Oxatis_Oxatis_SmallImage TEXT,
    PurchaseBillOfQuantitiesProgram_Program TEXT,
    CatalogId TEXT,
    CatalogItemId TEXT,
    EcotaxFurnitureId TEXT,
    PurchaseUnitPriceProgram_Program TEXT,
    LocalizableCaption_2 TEXT,
    LocalizableDesCom_2 TEXT,
    LocalizableDesCom_Clear_2 TEXT,
    LocalizableCaption_3 TEXT,
    LocalizableCaption_4 TEXT,
    LocalizableCaption_5 TEXT,
    LocalizableDesCom_3 TEXT,
    LocalizableDesCom_Clear_3 TEXT,
    LocalizableDesCom_4 TEXT,
    LocalizableDesCom_Clear_4 TEXT,
    LocalizableDesCom_5 TEXT,
    LocalizableDesCom_Clear_5 TEXT,
    IntrastatOriginCountryId TEXT,
    ParentRangeItemId TEXT,
    RangeTypeElementId0 TEXT,
    RangeTypeElementId1 TEXT,
    RangeTypeElementId2 TEXT,
    RangeTypeElementId3 TEXT,
    RangeTypeElementId4 TEXT,
    DefaultAllowedStorehouseId TEXT,
    MaintenanceContractTemplateId TEXT,
    GuaranteeTypeId TEXT,
    StockBillOfQuantitiesProgram_Program TEXT,
    PosThumbnail TEXT,
    GiftVoucherCashValue NUMERIC,
    GiftVoucherValidityDuration NUMERIC,
    IsExtraFee BOOLEAN,
    TimeUnitId TEXT,
    TechnicalDesCom TEXT,
    TechnicalDesComClear TEXT,
    LocalizableTechnicalDesCom_2 TEXT,
    LocalizableTechnicalDesCom_Clear_2 TEXT,
    LocalizableTechnicalDesCom_3 TEXT,
    LocalizableTechnicalDesCom_Clear_3 TEXT,
    LocalizableTechnicalDesCom_4 TEXT,
    LocalizableTechnicalDesCom_Clear_4 TEXT,
    LocalizableTechnicalDesCom_5 TEXT,
    LocalizableTechnicalDesCom_Clear_5 TEXT,
    CompetenceId TEXT,
    EquipmentTypeId TEXT,
    ScheduleEventTemplateId TEXT,
    CompetenceNumberToPlan NUMERIC,
    EquipmentTypeNumberToPlan NUMERIC,
    CadenceDuration NUMERIC,
    CadenceDurationType NUMERIC,
    CadenceDurationQuantity NUMERIC,
    InstallationTime NUMERIC,
    LabourCode TEXT,
    AutoUpdateLabourPrice BOOLEAN,
    IsEquipment BOOLEAN,
    InstallationCalculationType NUMERIC,
    MaterialPrices_PurchasePrice NUMERIC,
    MaterialPrices_ChargeRate NUMERIC,
    MaterialPrices_ChargeAmount NUMERIC,
    MaterialPrices_CostPrice NUMERIC,
    MaterialPrices_InterestRate NUMERIC,
    MaterialPrices_InterestAmount NUMERIC,
    MaterialPrices_SalePriceVatExcluded NUMERIC,
    MaterialPrices_BrandRate NUMERIC,
    MaterialPrices_VatId UUID,
    MaterialPrices_VatAmount NUMERIC,
    MaterialPrices_SalePriceVatIncluded NUMERIC,
    MaterialPrices_AdvisedSalePriceVATExcluded NUMERIC,
    MaterialPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    MaterialPrices_IsFixedPrice TEXT,
    MaterialPrices_EcotaxFurnitureId TEXT,
    LabourPrices_PurchasePrice NUMERIC,
    LabourPrices_ChargeRate NUMERIC,
    LabourPrices_ChargeAmount NUMERIC,
    LabourPrices_CostPrice NUMERIC,
    LabourPrices_InterestRate NUMERIC,
    LabourPrices_InterestAmount NUMERIC,
    LabourPrices_SalePriceVatExcluded NUMERIC,
    LabourPrices_BrandRate NUMERIC,
    LabourPrices_VatId UUID,
    LabourPrices_VatAmount NUMERIC,
    LabourPrices_SalePriceVatIncluded NUMERIC,
    LabourPrices_AdvisedSalePriceVATExcluded NUMERIC,
    LabourPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    LabourPrices_IsFixedPrice TEXT,
    LabourPrices_EcotaxFurnitureId TEXT,
    CanBePartiallyInvoiced BOOLEAN,
    PickMovementDisallowedOnTotallyBookedItem BOOLEAN,
    SalePriceModifiedDate TIMESTAMP,
    SalePriceModifiedUserId TEXT,
    TarifeoCode TEXT,
    TarifeoFullCode TEXT,
    TarifeoProducerId TEXT,
    ProducerName TEXT,
    TarifeoPriceDate TIMESTAMP,
    TarifeoPriceVersion TEXT,
    TarifeoUpdateDateTIme TIMESTAMP,
    IsSubscription BOOLEAN,
    SubscriptionPassings NUMERIC,
    SubscriptionTotalCostPrice NUMERIC,
    SubscriptionTotalPurchasePrice NUMERIC,
    SubscriptionTotalSalePriceVatExcluded NUMERIC,
    SubscriptionValidityDuration NUMERIC
);



CREATE TABLE IF NOT EXISTS event (
    id UUID PRIMARY KEY,
    xx_projet TEXT,
    payrollvariableduration0 NUMERIC,
    payrollvariableduration1 NUMERIC,
    payrollvariableduration2 NUMERIC,
    payrollvariableduration3 NUMERIC,
    payrollvariableduration4 NUMERIC,
    payrollvariableduration5 NUMERIC,
    payrollvariableduration6 NUMERIC,
    payrollvariableduration7 NUMERIC,
    payrollvariableduration8 NUMERIC,
    payrollvariableduration9 NUMERIC,
    payrollvariableduration10 NUMERIC,
    payrollvariableduration11 NUMERIC,
    payrollvariableduration12 NUMERIC,
    payrollvariableduration13 NUMERIC,
    payrollvariableduration14 NUMERIC,
    payrollvariableduration15 NUMERIC,
    payrollvariableduration16 NUMERIC,
    payrollvariableduration17 NUMERIC,
    payrollvariableduration18 NUMERIC,
    payrollvariableduration19 NUMERIC,
    payrollvariableduration20 NUMERIC,
    payrollvariableduration21 NUMERIC,
    payrollvariableduration22 NUMERIC,
    payrollvariableduration23 NUMERIC,
    payrollvariableduration24 NUMERIC,
    payrollvariableduration25 NUMERIC,
    payrollvariableduration26 NUMERIC,
    payrollvariableduration27 NUMERIC,
    payrollvariableduration28 NUMERIC,
    payrollvariableduration29 NUMERIC,
    payrollvariableduration30 NUMERIC,
    payrollvariableduration31 NUMERIC,
    payrollvariableduration32 NUMERIC,
    payrollvariableduration33 NUMERIC,
    payrollvariableduration34 NUMERIC,
    payrollvariableduration35 NUMERIC,
    payrollvariableduration36 NUMERIC,
    payrollvariableduration37 NUMERIC,
    payrollvariableduration38 NUMERIC,
    payrollvariableduration39 NUMERIC,
    payrollvariableduration40 NUMERIC,
    payrollvariableduration41 NUMERIC,
    payrollvariableduration42 NUMERIC,
    payrollvariableduration43 NUMERIC,
    payrollvariableduration44 NUMERIC,
    payrollvariableduration45 NUMERIC,
    payrollvariableduration46 NUMERIC,
    payrollvariableduration47 NUMERIC,
    payrollvariableduration48 NUMERIC,
    payrollvariableduration49 NUMERIC,
    eventstate SMALLINT,
    scheduleshowtimeline TEXT,
    linetype SMALLINT,
    lineorder INTEGER,
    startdatetime TIMESTAMP WITHOUT TIME ZONE,
    enddatetime TIMESTAMP WITHOUT TIME ZONE,
    caption TEXT,
    expectedduration_durationinhours NUMERIC,
    achievedduration_durationinhours NUMERIC,
    salepricevatexcluded NUMERIC,
    netamountvatexcluded NUMERIC,
    hourlycostprice NUMERIC,
    costamount NUMERIC,
    includeinrealizedcost SMALLINT,
    toinvoice TEXT,
    documenttype SMALLINT,
    address_npai TEXT,
    contact_naturalperson TEXT,
    contact_optin TEXT,
    reminderenabled TEXT,
    scheduleeventnumber TEXT,
    maintenance_invoicetravelexpenseonlastintervention SMALLINT,
    maintenance_sendconfirmationmail TEXT,
    maintenance_nexteventtoforesee TEXT,
    maintenance_decreasecontractcounterfornextevent TEXT,
    maintenance_includeinincidentpredictedcost SMALLINT,
    maintenance_includeincontractpredictedcost SMALLINT,
    invoiceinterveners TEXT,
    invoiceequipments TEXT,
    predictedcostamount NUMERIC,
    maintenance_nexteventdate TIMESTAMP WITHOUT TIME ZONE,
    maintenance_customerproductid TEXT,
    maintenance_nextmaintenanceeventid UUID,
    maintenance_contractid TEXT,
    maintenance_contracthoursnumberdecremented NUMERIC,
    maintenance_interventiondescription TEXT,
    maintenance_interventiondescriptionclear TEXT,
    maintenance_interventionreport TEXT,
    maintenance_interventionreportclear TEXT,
    maintenance_reference TEXT,
    maintenance_scheduleeventtemplateid TEXT,
    maintenance_travelduration NUMERIC,
    maintenance_incidentid TEXT,
    maintenance_travelexpenseid TEXT,
    maintenance_travelexpenseinvoiceid UUID,
    payrollexchangegroupid UUID,
    addressid UUID,
    contactid UUID,
    syseditcounter INTEGER,
    contact_externalid_googleid TEXT,
    contact_externalid_outlookid TEXT,
    creatorcolleagueid TEXT,
    customerid TEXT,
    supplierid TEXT,
    nextreminder TIMESTAMP WITHOUT TIME ZONE,
    remindertype SMALLINT,
    reminder SMALLINT,
    address_website TEXT,
    address_longitude NUMERIC,
    address_latitude NUMERIC,
    contact_civility TEXT,
    contact_name TEXT,
    contact_firstname TEXT,
    contact_phone TEXT,
    contact_cellphone TEXT,
    contact_fax TEXT,
    contact_email TEXT,
    contact_function TEXT,
    contact_department TEXT,
    saledocumentid UUID,
    purchasedocumentid UUID,
    stockdocumentid UUID,
    address_address1 TEXT,
    address_address2 TEXT,
    address_address3 TEXT,
    address_address4 TEXT,
    address_zipcode TEXT,
    address_city TEXT,
    address_state TEXT,
    address_countryisocode TEXT,
    address_description TEXT,
    address_civility TEXT,
    address_thirdname TEXT,
    itemid TEXT,
    invoicecolleagueid TEXT,
    invoicecustomerid TEXT,
    dealid TEXT,
    quantity NUMERIC,
    eventtype UUID,
    colleagueid TEXT,
    equipmentid TEXT,
    invoiceid UUID,
    invoicelineid UUID,
    parenteventid UUID,
    syscreateddate TIMESTAMP WITHOUT TIME ZONE,
    syscreateduser TEXT,
    sysmodifieddate TIMESTAMP WITHOUT TIME ZONE,
    sysmodifieduser TEXT,
    notesclear TEXT,
    notes TEXT,
    saledocumentlineid UUID,
    xx_gestion_projet_posit TEXT,
    xx_total_temps_realise NUMERIC,
    xx_total_temps_realise_client NUMERIC,
    xx_total_temps_realise_interne NUMERIC,
    xx_type_tache TEXT,
    xx_theme TEXT,
    xx_services TEXT,
    xx_theme_commercial TEXT,
    xx_duree_pevue NUMERIC,
    xx_total_temps_realise_relationnel NUMERIC,
    xx_duree_trajet NUMERIC,
    xx_activite TEXT,
    xx_total_temps_realise_trajet NUMERIC,
    xx_total_temps_realise_formation NUMERIC,
    xx_total_temps_realise_maquettage NUMERIC,
    subcontractorid TEXT,
    expectedduration_duration NUMERIC,
    expectedduration_unitid TEXT,
    expectedduration_editedduration TEXT,
    achievedduration_duration NUMERIC,
    achievedduration_unitid TEXT,
    achievedduration_editedduration TEXT,
    displaytype SMALLINT,
    competenceid TEXT,
    equipmenttypeid TEXT,
    constructionsiteid TEXT,
    exceptionworked TEXT,
    exceptioncompetenceids TEXT,
    exceptioncolleagueids TEXT,
    exceptioncolleagueselectiontype SMALLINT,
    exceptiondayschedule0_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule0_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule0_duration DOUBLE PRECISION,
    exceptiondayschedule0_active TEXT,
    exceptiondayschedule0_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule0_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule0_customize TEXT,
    exceptiondayschedule1_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule1_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule1_duration DOUBLE PRECISION,
    exceptiondayschedule1_active TEXT,
    exceptiondayschedule1_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule1_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule1_customize TEXT,
    exceptiondayschedule2_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule2_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule2_duration DOUBLE PRECISION,
    exceptiondayschedule2_active TEXT,
    exceptiondayschedule2_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule2_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule2_customize TEXT,
    exceptiondayschedule3_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule3_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule3_duration DOUBLE PRECISION,
    exceptiondayschedule3_active TEXT,
    exceptiondayschedule3_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule3_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule3_customize TEXT,
    exceptiondayschedule4_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule4_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule4_duration DOUBLE PRECISION,
    exceptiondayschedule4_active TEXT,
    exceptiondayschedule4_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule4_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule4_customize TEXT,
    exceptiondayschedule5_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule5_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule5_duration DOUBLE PRECISION,
    exceptiondayschedule5_active TEXT,
    exceptiondayschedule5_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule5_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule5_customize TEXT,
    exceptiondayschedule6_starttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule6_endtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule6_duration DOUBLE PRECISION,
    exceptiondayschedule6_active TEXT,
    exceptiondayschedule6_lunchstarttime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule6_lunchendtime TIMESTAMP WITHOUT TIME ZONE,
    exceptiondayschedule6_customize TEXT,
    isscheduleexception TEXT,
    mustbecalculated TEXT,
    createdbyexecutionquote TEXT,
    workingduration_durationinhours NUMERIC,
    workingduration_duration NUMERIC,
    workingduration_unitid TEXT,
    workingduration_editedduration TEXT,
    updatedworkingduration_durationinhours NUMERIC,
    updatedworkingduration_duration NUMERIC,
    updatedworkingduration_unitid TEXT,
    updatedworkingduration_editedduration TEXT,
    globalpercentcomplete SMALLINT,
    progressupdatelastdate TIMESTAMP WITHOUT TIME ZONE,
    labourupdatedexpectedduration_durationinhours NUMERIC,
    labourupdatedexpectedduration_duration NUMERIC,
    labourupdatedexpectedduration_unitid TEXT,
    labourupdatedexpectedduration_editedduration TEXT,
    labourscheduledduration_durationinhours NUMERIC,
    labourscheduledduration_duration NUMERIC,
    labourscheduledduration_unitid TEXT,
    labourscheduledduration_editedduration TEXT,
    labourpercentcomplete SMALLINT,
    labourremainingduration_durationinhours NUMERIC,
    labourremainingduration_duration NUMERIC,
    labourremainingduration_unitid TEXT,
    labourremainingduration_editedduration TEXT,
    labouroverduration_durationinhours NUMERIC,
    labouroverduration_duration NUMERIC,
    labouroverduration_unitid TEXT,
    labouroverduration_editedduration TEXT,
    occupancyrate SMALLINT,
    absencerange SMALLINT,
    datechangeremindenabled TEXT,
    conflicttypes INTEGER,
    conflictindicator SMALLINT,
    accountingyearid UUID,
    conflictimageindicator BYTEA,
    conflicttypesimage BYTEA,
    contact_allowusepersonnaldatas TEXT
);



-- Old version
CREATE TABLE IF NOT EXISTS event (
    id SERIAL PRIMARY KEY,
    Caption TEXT,
    StartDateTime DATE,
    EndDateTime DATE,
    ExpectedDuration_DurationInHours NUMERIC,
    AchievedDuration_DurationInHours NUMERIC,
    ScheduleEventNumber TEXT,
    InvoiceCustomerId TEXT,
    DealId TEXT,
    ColleagueId TEXT,
    NotesClear TEXT,
    xx_Type_Tache TEXT,
    xx_Theme TEXT,
    ExpectedDuration_Duration NUMERIC,
    ExpectedDuration_UnitId TEXT
);


--V2 MAUVAIS
CREATE TABLE Customer (
    CheckExceedCommitmentDate BOOLEAN,
    DueCommitmentsXDay BOOLEAN,
    EffectOfTradeAmount BOOLEAN,
    GenerateVCS BOOLEAN,
    ThirdLanguage VARCHAR(255),
    InvoicingChargesAmount DECIMAL(10, 2),
    AutomaticStockBooking BOOLEAN,
    CustomerToUseInCustomerProducts BOOLEAN,
    ExtendedCurrentAmount DECIMAL(10, 2),
    ThresholdBeforeExceedAmount DECIMAL(10, 2),
    Name VARCHAR(255),
    UseInvoicingAddressAsDeliveryAddress BOOLEAN,
    UseInvoicingContactAsDeliveryContact BOOLEAN,
    MainDeliveryAddress_Npai BOOLEAN,
    MainInvoicingAddress_Npai BOOLEAN,
    MainDeliveryContact_NaturalPerson BOOLEAN,
    MainDeliveryContact_OptIn BOOLEAN,
    Id SERIAL PRIMARY KEY,
    MainInvoicingContact_NaturalPerson BOOLEAN,
    MainInvoicingContact_OptIn BOOLEAN,
    NaturalPerson BOOLEAN,
    TerritorialityId INT,
    FinancialDiscountType VARCHAR(255),
    FinancialDiscountRate DECIMAL(5, 2),
    FinancialDiscountPaymentDelay INT,
    ActiveState BOOLEAN,
    DiscountRate DECIMAL(5, 2),
    SecondDiscountRate DECIMAL(5, 2),
    AllowedAmount DECIMAL(10, 2),
    CurrentAmount DECIMAL(10, 2),
    InitialAmount DECIMAL(10, 2),
    ExceedAmount DECIMAL(10, 2),
    MustRetrieveCommitmentsFromAccounting BOOLEAN,
    PriceWithTaxBased BOOLEAN,
    MustBeReminder BOOLEAN,
    DayNumberToFirstReminder INT,
    DayNumberToSecondReminder INT,
    DayNumberToThirdReminder INT,
    IsCustomerAccount BOOLEAN,
    WebContactSendKind VARCHAR(255),
    SubjectToRE BOOLEAN,
    UniqueId UUID,
    DisallowOrderAssort BOOLEAN,
    DisallowDeliveryAssort BOOLEAN,
    SendReminderToPayerThird BOOLEAN,
    xx_Envoi_carte_voeux BOOLEAN,
    AssortDeliveryByOrder BOOLEAN,
    CreatePosDeliveryOrderByDefault BOOLEAN,
    LoyaltyOriginReportType VARCHAR(255),
    LoyaltyOriginReportValue DECIMAL(10, 2),
    LoyaltyValue DECIMAL(10, 2),
    LoyaltyCardType VARCHAR(255),
    LoyaltyCardId SERIAL,
    LoyaltyCardCreationDate DATE,
    LoyaltyCardValidityDuration INT,
    LoyaltyCardExpiryDate DATE,
    LoyaltyCardRenewalDate DATE,
    sysRecordVersion INT,
    sysRecordVersionId UUID,
    sysEditCounter INT,
    SelectedReminderReport VARCHAR(255),
    ShippingId INT,
    DocumentSerialId SERIAL,
    IdentificationType VARCHAR(255),
    AnalyticAccounting_GridId INT,
    Type VARCHAR(255),
    Accounts_Account VARCHAR(255),
    CurrencyId INT,
    Group1 VARCHAR(255),
    Group2 VARCHAR(255),
    ColleagueId INT,
    FirstInvoicingDate DATE,
    SettlementModeId INT,
    PaymentDate DATE,
    PriceListCategoryId INT,
    Siren VARCHAR(255),
    NAF VARCHAR(255),
    FamilyId INT,
    SubFamilyId INT,
    IntracommunityVATNumber VARCHAR(255),
    MainInvoicingContact_ExternalId_GoogleId UUID,
    MainInvoicingContact_ExternalId_OutlookId UUID,
    Civility VARCHAR(255),
    MainDeliveryContact_ExternalId_GoogleId UUID,
    MainDeliveryContact_ExternalId_OutlookId UUID,
    MainInvoicingContact_Civility VARCHAR(255),
    MainInvoicingContact_Name VARCHAR(255),
    MainInvoicingContact_FirstName VARCHAR(255),
    MainInvoicingContact_Phone VARCHAR(255),
    MainInvoicingContact_CellPhone VARCHAR(255),
    MainInvoicingContact_Fax VARCHAR(255),
    MainInvoicingContact_Email VARCHAR(255),
    MainInvoicingContact_Function VARCHAR(255),
    MainInvoicingContact_Department VARCHAR(255),
    MainInvoicingAddress_WebSite VARCHAR(255),
    MainInvoicingAddress_Longitude DECIMAL(9, 6),
    MainInvoicingAddress_Latitude DECIMAL(9, 6),
    MainDeliveryContact_Civility VARCHAR(255),
    MainDeliveryContact_Name VARCHAR(255),
    MainDeliveryContact_FirstName VARCHAR(255),
    MainDeliveryContact_Phone VARCHAR(255),
    MainDeliveryContact_CellPhone VARCHAR(255),
    MainDeliveryContact_Fax VARCHAR(255),
    MainDeliveryContact_Email VARCHAR(255),
    MainDeliveryContact_Function VARCHAR(255),
    MainDeliveryContact_Department VARCHAR(255),
    MainDeliveryAddress_WebSite VARCHAR(255),
    MainDeliveryAddress_Longitude DECIMAL(9, 6),
    MainDeliveryAddress_Latitude DECIMAL(9, 6),
    MainInvoicingAddress_Address1 VARCHAR(255),
    MainInvoicingAddress_Address2 VARCHAR(255),
    MainInvoicingAddress_Address3 VARCHAR(255),
    MainInvoicingAddress_Address4 VARCHAR(255),
    MainInvoicingAddress_ZipCode VARCHAR(255),
    MainInvoicingAddress_City VARCHAR(255),
    MainInvoicingAddress_State VARCHAR(255),
    MainInvoicingAddress_CountryIsoCode VARCHAR(255),
    MainInvoicingAddress_Description TEXT,
    MainInvoicingAddress_Civility VARCHAR(255),
    MainInvoicingAddress_ThirdName VARCHAR(255),
    MainDeliveryAddress_Address1 VARCHAR(255),
    MainDeliveryAddress_Address2 VARCHAR(255),
    MainDeliveryAddress_Address3 VARCHAR(255),
    MainDeliveryAddress_Address4 VARCHAR(255),
    MainDeliveryAddress_ZipCode VARCHAR(255),
    MainDeliveryAddress_City VARCHAR(255),
    MainDeliveryAddress_State VARCHAR(255),
    MainDeliveryAddress_CountryIsoCode VARCHAR(255),
    MainDeliveryAddress_Description TEXT,
    MainDeliveryAddress_Civility VARCHAR(255),
    MainDeliveryAddress_ThirdName VARCHAR(255),
    sysCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysCreatedUser VARCHAR(255),
    sysModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysModifiedUser VARCHAR(255),
    NotesClear TEXT,
    Notes TEXT,
    Accounts_BillOfExchangeAccountingAccount VARCHAR(255),
    TaxIds0 VARCHAR(255),
    TaxIds1 VARCHAR(255),
    TaxIds2 VARCHAR(255),
    PaymentThirdId INT,
    InvoicingThirdId INT,
    InvoicingChargesVatId INT,
    LastInvoicingDate DATE,
    DocumentPrintMention TEXT,
    StorehouseId INT,
    Accounts_AuxiliaryAccount VARCHAR(255),
    Accounts_DoubtfulAccount VARCHAR(255),
    SchedulerColor VARCHAR(255),
    TravelExpenseId INT,
    Accounts_SecurityBondAccount VARCHAR(255),
    Accounts_SecurityBondForGoodCompletedWorkAccount VARCHAR(255),
    ShowTechnicalSheetOnFront TEXT,
    TechnicalSheetClear TEXT,
    TechnicalSheet TEXT,
    MainDeliveryContact_AllowUsePersonnalDatas TEXT,
    MainInvoicingContact_AllowUsePersonnalDatas TEXT,
    AllowUsePersonnalDatas BOOLEAN,
    Nic VARCHAR(255),
    LoyaltyCumulativeTurnoverReport TEXT,
    LoyaltyCumulativeTurnover DECIMAL(10, 2),
    DepositPercentage DECIMAL(5, 2),
    SecurityBondRate DECIMAL(5, 2),
    SecurityBondRateForGoodCompletedWork DECIMAL(5, 2),
    BuyerReference VARCHAR(255),
    GoCardLessThirdId UUID,
    DefaultBankAccountId INT
);

CREATE TABLE Item (
    BarCodePrice DECIMAL(10, 2),
    BarCodeWeight DECIMAL(10, 2),
    PosAddItem BOOLEAN,
    LoyaltyPoints INT,
    CalculateLoyaltyFrom DATE,
    GiftVoucher BOOLEAN,
    IntrastatExcluded BOOLEAN,
    CreateCustomerProductInCustomerPark BOOLEAN,
    IsMaintenanceContract BOOLEAN,
    IsGuaranteeExtension BOOLEAN,
    CustomerParkCreation DATE,
    StockBookingAllowed BOOLEAN,
    AutomaticStockBooking BOOLEAN,
    IncludeToRecursiveReplenishment BOOLEAN,
    IncludeToFabricationReplenishment BOOLEAN,
    IncludeToSupplierReplenishment BOOLEAN,
    CadenceQuantity INT,
    CadenceNumberOfDays INT,
    DoNotAssortAssemblyRequestsWithDifferentDates BOOLEAN,
    MaximumGapDayToAssort INT,
    NomenclatureAccountingTransferTypeForSale VARCHAR(255),
    NomenclatureAccountingTransferTypeForPurchase VARCHAR(255),
    VirtualPump BOOLEAN,
    VirtualStockValue DECIMAL(10, 2),
    BookedQuantity INT,
    PurchaseBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    NotOnMarket BOOLEAN,
    PurchaseUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    CanBePartiallyDelivered BOOLEAN,
    Caption VARCHAR(255),
    Oxatis_Oxatis_HandlingSurcharge1ST DECIMAL(10, 2),
    Oxatis_Oxatis_HandlingSurchargeOthers DECIMAL(10, 2),
    InterventionDurationEqualsQuantity BOOLEAN,
    Height DECIMAL(10, 2),
    Width DECIMAL(10, 2),
    Length DECIMAL(10, 2),
    Oxatis_Oxatis_UseSubFamilyAsBrand BOOLEAN,
    IsManagedByCounterMark BOOLEAN,
    IsCounterMarkForced BOOLEAN,
    SalePurchaseConversionRate DECIMAL(10, 2),
    LimitDateMode VARCHAR(255),
    LimitDateSafetyDelay INT,
    UniqueId VARCHAR(255),
    PurchasePrice DECIMAL(10, 2),
    ChargeRate DECIMAL(10, 2),
    ChargeAmount DECIMAL(10, 2),
    CostPrice DECIMAL(10, 2),
    InterestRate DECIMAL(10, 2),
    InterestAmount DECIMAL(10, 2),
    SalePriceVatExcluded DECIMAL(10, 2),
    BrandRate DECIMAL(10, 2),
    VatAmount DECIMAL(10, 2),
    SalePriceVatIncluded DECIMAL(10, 2),
    ManageStock BOOLEAN,
    RealStock INT,
    Pump VARCHAR(255),
    StockValue DECIMAL(10, 2),
    OrderedQuantity INT,
    SuppliersOrderedQuantity INT,
    VirtualStock INT,
    DefaultQuantity INT,
    Volume DECIMAL(10, 2),
    Weight DECIMAL(10, 2),
    NetWeight DECIMAL(10, 2),
    ComponentsPurchasePrice DECIMAL(10, 2),
    ComponentsCostPrice DECIMAL(10, 2),
    ComponentsSalePriceVatExcluded DECIMAL(10, 2),
    ComponentsSalePriceVatIncluded DECIMAL(10, 2),
    PrintComponentDetail BOOLEAN,
    AssemblingVirtualQuantity INT,
    DisassemblingQuantity INT,
    QuantityUsedToAssemblate INT,
    QuantityFromDisassembling INT,
    AllowNegativeStock BOOLEAN,
    UseComponentVat BOOLEAN,
    ApplyPriceListOnComponents BOOLEAN,
    ActiveState BOOLEAN,
    AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    TrackingMode VARCHAR(255),
    AllowComponentsModification BOOLEAN,
    AllowPublishOnWeb BOOLEAN,
    ImageVersion VARCHAR(255),
    PriceDecimalNumber INT,
    IsHumanServicesIncludedInAttestation BOOLEAN,
    Oxatis_Oxatis_ShowInStockNote BOOLEAN,
    Oxatis_Oxatis_ShowStockLevel BOOLEAN,
    Oxatis_Oxatis_ShowIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStockScenario VARCHAR(255),
    Oxatis_Oxatis_ShowDaysToship BOOLEAN,
    Oxatis_Oxatis_ShipPrice DECIMAL(10, 2),
    Oxatis_Oxatis_DaysToship INT,
    Oxatis_Oxatis_UserMainSupplierDaysToship INT,
    Id INT,
    ItemType VARCHAR(255),
    BillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    SaleUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    UpdateComponentsStockInFabrication BOOLEAN,
    CustomersDeliveryOrderPreparingQuantity INT,
    CustomersReturnOrderPreparingQuantity INT,
    SuppliersDeliveryOrderPreparingQuantity INT,
    SuppliersReturnOrderPreparingQuantity INT,
    StockBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    PurchaseChargesRate DECIMAL(10, 2),
    PosIsScale BOOLEAN,
    PosTare DECIMAL(10, 2),
    BillOfQuantitiesProgram_Program VARCHAR(255),
    ReplenishmentDeliveryAddressType VARCHAR(255),
    SaleUnitPriceProgram_Program VARCHAR(255),
    DesCom TEXT,
    DesComClear TEXT,
    ItemImage VARCHAR(255),
    BarCode VARCHAR(255),
    UnitId INT,
    FamilyId INT,
    SubFamilyId INT,
    sysCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysCreatedUser VARCHAR(255),
    sysModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysModifiedUser VARCHAR(255),
    NotesClear TEXT,
    Notes TEXT,
    Oxatis_Oxatis_CategoryType1 VARCHAR(255),
    Oxatis_Oxatis_CategoryType2 VARCHAR(255),
    Oxatis_Oxatis_CategoryType3 VARCHAR(255),
    Oxatis_Oxatis_CategoryId1 INT,
    Oxatis_Oxatis_CategoryId2 INT,
    Oxatis_Oxatis_CategoryId3 INT,
    Oxatis_Oxatis_MetaTitle TEXT,
    Oxatis_Oxatis_MetaDescription TEXT,
    Oxatis_Oxatis_MetaKeywords TEXT,
    Oxatis_Oxatis_Brand VARCHAR(255),
    MainIntervener VARCHAR(255),
    IntrastatNc8NomenclatureId INT,
    Group1 VARCHAR(255),
    Group2 VARCHAR(255),
    NotPrintable BOOLEAN,
    NotIncluded BOOLEAN,
    IsFixedPrice BOOLEAN,
    NonInvoiceableType VARCHAR(255),
    ComponentCalculationType VARCHAR(255),
    ReplacementItem INT,
    WeightUnitId INT,
    NumberOfItemByPackage INT,
    VolumeUnitId INT,
    SupplierId INT,
    EcotaxId INT,
    StockDestination VARCHAR(255),
    StockVarianceAccount VARCHAR(255),
    CurrentStockAccount VARCHAR(255),
    VatId INT,
    sysModuleId INT,
    sysDatabaseId INT,
    sysRecordVersion INT,
    sysRecordVersionId INT,
    sysEditCounter INT,
    LimitDateSafetyDelayMode VARCHAR(255),
    DefaultLifeTime INT,
    PurchasePriceUpdateType VARCHAR(255),
    AnalyticAccounting_GridId INT,
    PurchaseUnitId INT,
    DimensionUnitId INT,
    Oxatis_Oxatis_LongDescription TEXT,
    Oxatis_Oxatis_LongDescriptionClear TEXT,
    Oxatis_Oxatis_SmallImage VARCHAR(255),
    PurchaseBillOfQuantitiesProgram_Program VARCHAR(255),
    CatalogId INT,
    CatalogItemId INT,
    EcotaxFurnitureId INT,
    PurchaseUnitPriceProgram_Program VARCHAR(255),
    LocalizableCaption_2 TEXT,
    LocalizableDesCom_2 TEXT,
    LocalizableDesCom_Clear_2 TEXT,
    LocalizableCaption_3 TEXT,
    LocalizableCaption_4 TEXT,
    LocalizableCaption_5 TEXT,
    LocalizableDesCom_3 TEXT,
    LocalizableDesCom_Clear_3 TEXT,
    LocalizableDesCom_4 TEXT,
    LocalizableDesCom_Clear_4 TEXT,
    LocalizableDesCom_5 TEXT,
    LocalizableDesCom_Clear_5 TEXT,
    IntrastatOriginCountryId INT,
    ParentRangeItemId INT,
    RangeTypeElementId0 INT,
    RangeTypeElementId1 INT,
    RangeTypeElementId2 INT,
    RangeTypeElementId3 INT,
    RangeTypeElementId4 INT,
    DefaultAllowedStorehouseId INT,
    MaintenanceContractTemplateId INT,
    GuaranteeTypeId INT,
    StockBillOfQuantitiesProgram_Program VARCHAR(255),
    PosThumbnail VARCHAR(255),
    GiftVoucherCashValue DECIMAL(10, 2),
    GiftVoucherValidityDuration INT,
    IsExtraFee BOOLEAN,
    TimeUnitId INT,
    TechnicalDesCom TEXT,
    TechnicalDesComClear TEXT,
    LocalizableTechnicalDesCom_2 TEXT,
    LocalizableTechnicalDesCom_Clear_2 TEXT,
    LocalizableTechnicalDesCom_3 TEXT,
    LocalizableTechnicalDesCom_Clear_3 TEXT,
    LocalizableTechnicalDesCom_4 TEXT,
    LocalizableTechnicalDesCom_Clear_4 TEXT,
    LocalizableTechnicalDesCom_5 TEXT,
    LocalizableTechnicalDesCom_Clear_5 TEXT,
    CompetenceId INT,
    EquipmentTypeId INT,
    ScheduleEventTemplateId INT,
    CompetenceNumberToPlan INT,
    EquipmentTypeNumberToPlan INT,
    CadenceDuration INT,
    CadenceDurationType VARCHAR(255),
    CadenceDurationQuantity INT,
    InstallationTime INT,
    LabourCode VARCHAR(255),
    AutoUpdateLabourPrice BOOLEAN,
    IsEquipment BOOLEAN,
    InstallationCalculationType VARCHAR(255),
    MaterialPrices_PurchasePrice DECIMAL(10, 2),
    MaterialPrices_ChargeRate DECIMAL(10, 2),
    MaterialPrices_ChargeAmount DECIMAL(10, 2),
    MaterialPrices_CostPrice DECIMAL(10, 2),
    MaterialPrices_InterestRate DECIMAL(10, 2),
    MaterialPrices_InterestAmount DECIMAL(10, 2),
    MaterialPrices_SalePriceVatExcluded DECIMAL(10, 2),
    MaterialPrices_BrandRate DECIMAL(10, 2),
    MaterialPrices_VatId INT,
    MaterialPrices_VatAmount DECIMAL(10, 2),
    MaterialPrices_SalePriceVatIncluded DECIMAL(10, 2),
    MaterialPrices_AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    MaterialPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    MaterialPrices_IsFixedPrice BOOLEAN,
    MaterialPrices_EcotaxFurnitureId INT,
    LabourPrices_PurchasePrice DECIMAL(10, 2),
    LabourPrices_ChargeRate DECIMAL(10, 2),
    LabourPrices_ChargeAmount DECIMAL(10, 2),
    LabourPrices_CostPrice DECIMAL(10, 2),
    LabourPrices_InterestRate DECIMAL(10, 2),
    LabourPrices_InterestAmount DECIMAL(10, 2),
    LabourPrices_SalePriceVatExcluded DECIMAL(10, 2),
    LabourPrices_BrandRate DECIMAL(10, 2),
    LabourPrices_VatId INT,
    LabourPrices_VatAmount DECIMAL(10, 2),
    LabourPrices_SalePriceVatIncluded DECIMAL(10, 2),
    LabourPrices_AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    LabourPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    LabourPrices_IsFixedPrice BOOLEAN,
    LabourPrices_EcotaxFurnitureId INT,
    CanBePartiallyInvoiced BOOLEAN,
    PickMovementDisallowedOnTotallyBookedItem BOOLEAN,
    SalePriceModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SalePriceModifiedUserId VARCHAR(255),
    TarifeoCode VARCHAR(255),
    TarifeoFullCode VARCHAR(255),
    TarifeoProducerId INT,
    ProducerName VARCHAR(255),
    TarifeoPriceDate DATE,
    TarifeoPriceVersion INT,
    TarifeoUpdateDateTIme TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IsSubscription BOOLEAN,
    SubscriptionPassings INT,
    SubscriptionTotalCostPrice DECIMAL(10, 2),
    SubscriptionTotalPurchasePrice DECIMAL(10, 2),
    SubscriptionTotalSalePriceVatExcluded DECIMAL(10, 2),
    SubscriptionValidityDuration INT
);

