
--V2
CREATE TABLE Customer (
    CheckExceedCommitmentDate BOOLEAN,
    DueCommitmentsXDay BOOLEAN,
    EffectOfTradeAmount BOOLEAN,
    GenerateVCS BOOLEAN,
    ThirdLanguage VARCHAR(255),
    InvoicingChargesAmount DECIMAL(10, 2),
    AutomaticStockBooking BOOLEAN,
    CustomerToUseInCustomerProducts BOOLEAN,
    ExtendedCurrentAmount DECIMAL(10, 2),
    ThresholdBeforeExceedAmount DECIMAL(10, 2),
    Name VARCHAR(255),
    UseInvoicingAddressAsDeliveryAddress BOOLEAN,
    UseInvoicingContactAsDeliveryContact BOOLEAN,
    MainDeliveryAddress_Npai BOOLEAN,
    MainInvoicingAddress_Npai BOOLEAN,
    MainDeliveryContact_NaturalPerson BOOLEAN,
    MainDeliveryContact_OptIn BOOLEAN,
    Id SERIAL PRIMARY KEY,
    MainInvoicingContact_NaturalPerson BOOLEAN,
    MainInvoicingContact_OptIn BOOLEAN,
    NaturalPerson BOOLEAN,
    TerritorialityId INT,
    FinancialDiscountType VARCHAR(255),
    FinancialDiscountRate DECIMAL(5, 2),
    FinancialDiscountPaymentDelay INT,
    ActiveState BOOLEAN,
    DiscountRate DECIMAL(5, 2),
    SecondDiscountRate DECIMAL(5, 2),
    AllowedAmount DECIMAL(10, 2),
    CurrentAmount DECIMAL(10, 2),
    InitialAmount DECIMAL(10, 2),
    ExceedAmount DECIMAL(10, 2),
    MustRetrieveCommitmentsFromAccounting BOOLEAN,
    PriceWithTaxBased BOOLEAN,
    MustBeReminder BOOLEAN,
    DayNumberToFirstReminder INT,
    DayNumberToSecondReminder INT,
    DayNumberToThirdReminder INT,
    IsCustomerAccount BOOLEAN,
    WebContactSendKind VARCHAR(255),
    SubjectToRE BOOLEAN,
    UniqueId UUID,
    DisallowOrderAssort BOOLEAN,
    DisallowDeliveryAssort BOOLEAN,
    SendReminderToPayerThird BOOLEAN,
    xx_Envoi_carte_voeux BOOLEAN,
    AssortDeliveryByOrder BOOLEAN,
    CreatePosDeliveryOrderByDefault BOOLEAN,
    LoyaltyOriginReportType VARCHAR(255),
    LoyaltyOriginReportValue DECIMAL(10, 2),
    LoyaltyValue DECIMAL(10, 2),
    LoyaltyCardType VARCHAR(255),
    LoyaltyCardId SERIAL,
    LoyaltyCardCreationDate DATE,
    LoyaltyCardValidityDuration INT,
    LoyaltyCardExpiryDate DATE,
    LoyaltyCardRenewalDate DATE,
    sysRecordVersion INT,
    sysRecordVersionId UUID,
    sysEditCounter INT,
    SelectedReminderReport VARCHAR(255),
    ShippingId INT,
    DocumentSerialId SERIAL,
    IdentificationType VARCHAR(255),
    AnalyticAccounting_GridId INT,
    Type VARCHAR(255),
    Accounts_Account VARCHAR(255),
    CurrencyId INT,
    Group1 VARCHAR(255),
    Group2 VARCHAR(255),
    ColleagueId INT,
    FirstInvoicingDate DATE,
    SettlementModeId INT,
    PaymentDate DATE,
    PriceListCategoryId INT,
    Siren VARCHAR(255),
    NAF VARCHAR(255),
    FamilyId INT,
    SubFamilyId INT,
    IntracommunityVATNumber VARCHAR(255),
    MainInvoicingContact_ExternalId_GoogleId UUID,
    MainInvoicingContact_ExternalId_OutlookId UUID,
    Civility VARCHAR(255),
    MainDeliveryContact_ExternalId_GoogleId UUID,
    MainDeliveryContact_ExternalId_OutlookId UUID,
    MainInvoicingContact_Civility VARCHAR(255),
    MainInvoicingContact_Name VARCHAR(255),
    MainInvoicingContact_FirstName VARCHAR(255),
    MainInvoicingContact_Phone VARCHAR(255),
    MainInvoicingContact_CellPhone VARCHAR(255),
    MainInvoicingContact_Fax VARCHAR(255),
    MainInvoicingContact_Email VARCHAR(255),
    MainInvoicingContact_Function VARCHAR(255),
    MainInvoicingContact_Department VARCHAR(255),
    MainInvoicingAddress_WebSite VARCHAR(255),
    MainInvoicingAddress_Longitude DECIMAL(9, 6),
    MainInvoicingAddress_Latitude DECIMAL(9, 6),
    MainDeliveryContact_Civility VARCHAR(255),
    MainDeliveryContact_Name VARCHAR(255),
    MainDeliveryContact_FirstName VARCHAR(255),
    MainDeliveryContact_Phone VARCHAR(255),
    MainDeliveryContact_CellPhone VARCHAR(255),
    MainDeliveryContact_Fax VARCHAR(255),
    MainDeliveryContact_Email VARCHAR(255),
    MainDeliveryContact_Function VARCHAR(255),
    MainDeliveryContact_Department VARCHAR(255),
    MainDeliveryAddress_WebSite VARCHAR(255),
    MainDeliveryAddress_Longitude DECIMAL(9, 6),
    MainDeliveryAddress_Latitude DECIMAL(9, 6),
    MainInvoicingAddress_Address1 VARCHAR(255),
    MainInvoicingAddress_Address2 VARCHAR(255),
    MainInvoicingAddress_Address3 VARCHAR(255),
    MainInvoicingAddress_Address4 VARCHAR(255),
    MainInvoicingAddress_ZipCode VARCHAR(255),
    MainInvoicingAddress_City VARCHAR(255),
    MainInvoicingAddress_State VARCHAR(255),
    MainInvoicingAddress_CountryIsoCode VARCHAR(255),
    MainInvoicingAddress_Description TEXT,
    MainInvoicingAddress_Civility VARCHAR(255),
    MainInvoicingAddress_ThirdName VARCHAR(255),
    MainDeliveryAddress_Address1 VARCHAR(255),
    MainDeliveryAddress_Address2 VARCHAR(255),
    MainDeliveryAddress_Address3 VARCHAR(255),
    MainDeliveryAddress_Address4 VARCHAR(255),
    MainDeliveryAddress_ZipCode VARCHAR(255),
    MainDeliveryAddress_City VARCHAR(255),
    MainDeliveryAddress_State VARCHAR(255),
    MainDeliveryAddress_CountryIsoCode VARCHAR(255),
    MainDeliveryAddress_Description TEXT,
    MainDeliveryAddress_Civility VARCHAR(255),
    MainDeliveryAddress_ThirdName VARCHAR(255),
    sysCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysCreatedUser VARCHAR(255),
    sysModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysModifiedUser VARCHAR(255),
    NotesClear TEXT,
    Notes TEXT,
    Accounts_BillOfExchangeAccountingAccount VARCHAR(255),
    TaxIds0 VARCHAR(255),
    TaxIds1 VARCHAR(255),
    TaxIds2 VARCHAR(255),
    PaymentThirdId INT,
    InvoicingThirdId INT,
    InvoicingChargesVatId INT,
    LastInvoicingDate DATE,
    DocumentPrintMention TEXT,
    StorehouseId INT,
    Accounts_AuxiliaryAccount VARCHAR(255),
    Accounts_DoubtfulAccount VARCHAR(255),
    SchedulerColor VARCHAR(255),
    TravelExpenseId INT,
    Accounts_SecurityBondAccount VARCHAR(255),
    Accounts_SecurityBondForGoodCompletedWorkAccount VARCHAR(255),
    ShowTechnicalSheetOnFront TEXT,
    TechnicalSheetClear TEXT,
    TechnicalSheet TEXT,
    MainDeliveryContact_AllowUsePersonnalDatas TEXT,
    MainInvoicingContact_AllowUsePersonnalDatas TEXT,
    AllowUsePersonnalDatas BOOLEAN,
    Nic VARCHAR(255),
    LoyaltyCumulativeTurnoverReport TEXT,
    LoyaltyCumulativeTurnover DECIMAL(10, 2),
    DepositPercentage DECIMAL(5, 2),
    SecurityBondRate DECIMAL(5, 2),
    SecurityBondRateForGoodCompletedWork DECIMAL(5, 2),
    BuyerReference VARCHAR(255),
    GoCardLessThirdId UUID,
    DefaultBankAccountId INT
);

CREATE TABLE Item (
    BarCodePrice DECIMAL(10, 2),
    BarCodeWeight DECIMAL(10, 2),
    PosAddItem BOOLEAN,
    LoyaltyPoints INT,
    CalculateLoyaltyFrom DATE,
    GiftVoucher BOOLEAN,
    IntrastatExcluded BOOLEAN,
    CreateCustomerProductInCustomerPark BOOLEAN,
    IsMaintenanceContract BOOLEAN,
    IsGuaranteeExtension BOOLEAN,
    CustomerParkCreation DATE,
    StockBookingAllowed BOOLEAN,
    AutomaticStockBooking BOOLEAN,
    IncludeToRecursiveReplenishment BOOLEAN,
    IncludeToFabricationReplenishment BOOLEAN,
    IncludeToSupplierReplenishment BOOLEAN,
    CadenceQuantity INT,
    CadenceNumberOfDays INT,
    DoNotAssortAssemblyRequestsWithDifferentDates BOOLEAN,
    MaximumGapDayToAssort INT,
    NomenclatureAccountingTransferTypeForSale VARCHAR(255),
    NomenclatureAccountingTransferTypeForPurchase VARCHAR(255),
    VirtualPump BOOLEAN,
    VirtualStockValue DECIMAL(10, 2),
    BookedQuantity INT,
    PurchaseBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    NotOnMarket BOOLEAN,
    PurchaseUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    CanBePartiallyDelivered BOOLEAN,
    Caption VARCHAR(255),
    Oxatis_Oxatis_HandlingSurcharge1ST DECIMAL(10, 2),
    Oxatis_Oxatis_HandlingSurchargeOthers DECIMAL(10, 2),
    InterventionDurationEqualsQuantity BOOLEAN,
    Height DECIMAL(10, 2),
    Width DECIMAL(10, 2),
    Length DECIMAL(10, 2),
    Oxatis_Oxatis_UseSubFamilyAsBrand BOOLEAN,
    IsManagedByCounterMark BOOLEAN,
    IsCounterMarkForced BOOLEAN,
    SalePurchaseConversionRate DECIMAL(10, 2),
    LimitDateMode VARCHAR(255),
    LimitDateSafetyDelay INT,
    UniqueId VARCHAR(255),
    PurchasePrice DECIMAL(10, 2),
    ChargeRate DECIMAL(10, 2),
    ChargeAmount DECIMAL(10, 2),
    CostPrice DECIMAL(10, 2),
    InterestRate DECIMAL(10, 2),
    InterestAmount DECIMAL(10, 2),
    SalePriceVatExcluded DECIMAL(10, 2),
    BrandRate DECIMAL(10, 2),
    VatAmount DECIMAL(10, 2),
    SalePriceVatIncluded DECIMAL(10, 2),
    ManageStock BOOLEAN,
    RealStock INT,
    Pump VARCHAR(255),
    StockValue DECIMAL(10, 2),
    OrderedQuantity INT,
    SuppliersOrderedQuantity INT,
    VirtualStock INT,
    DefaultQuantity INT,
    Volume DECIMAL(10, 2),
    Weight DECIMAL(10, 2),
    NetWeight DECIMAL(10, 2),
    ComponentsPurchasePrice DECIMAL(10, 2),
    ComponentsCostPrice DECIMAL(10, 2),
    ComponentsSalePriceVatExcluded DECIMAL(10, 2),
    ComponentsSalePriceVatIncluded DECIMAL(10, 2),
    PrintComponentDetail BOOLEAN,
    AssemblingVirtualQuantity INT,
    DisassemblingQuantity INT,
    QuantityUsedToAssemblate INT,
    QuantityFromDisassembling INT,
    AllowNegativeStock BOOLEAN,
    UseComponentVat BOOLEAN,
    ApplyPriceListOnComponents BOOLEAN,
    ActiveState BOOLEAN,
    AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    TrackingMode VARCHAR(255),
    AllowComponentsModification BOOLEAN,
    AllowPublishOnWeb BOOLEAN,
    ImageVersion VARCHAR(255),
    PriceDecimalNumber INT,
    IsHumanServicesIncludedInAttestation BOOLEAN,
    Oxatis_Oxatis_ShowInStockNote BOOLEAN,
    Oxatis_Oxatis_ShowStockLevel BOOLEAN,
    Oxatis_Oxatis_ShowIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStockScenario VARCHAR(255),
    Oxatis_Oxatis_ShowDaysToship BOOLEAN,
    Oxatis_Oxatis_ShipPrice DECIMAL(10, 2),
    Oxatis_Oxatis_DaysToship INT,
    Oxatis_Oxatis_UserMainSupplierDaysToship INT,
    Id INT,
    ItemType VARCHAR(255),
    BillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    SaleUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    UpdateComponentsStockInFabrication BOOLEAN,
    CustomersDeliveryOrderPreparingQuantity INT,
    CustomersReturnOrderPreparingQuantity INT,
    SuppliersDeliveryOrderPreparingQuantity INT,
    SuppliersReturnOrderPreparingQuantity INT,
    StockBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    PurchaseChargesRate DECIMAL(10, 2),
    PosIsScale BOOLEAN,
    PosTare DECIMAL(10, 2),
    BillOfQuantitiesProgram_Program VARCHAR(255),
    ReplenishmentDeliveryAddressType VARCHAR(255),
    SaleUnitPriceProgram_Program VARCHAR(255),
    DesCom TEXT,
    DesComClear TEXT,
    ItemImage VARCHAR(255),
    BarCode VARCHAR(255),
    UnitId INT,
    FamilyId INT,
    SubFamilyId INT,
    sysCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysCreatedUser VARCHAR(255),
    sysModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sysModifiedUser VARCHAR(255),
    NotesClear TEXT,
    Notes TEXT,
    Oxatis_Oxatis_CategoryType1 VARCHAR(255),
    Oxatis_Oxatis_CategoryType2 VARCHAR(255),
    Oxatis_Oxatis_CategoryType3 VARCHAR(255),
    Oxatis_Oxatis_CategoryId1 INT,
    Oxatis_Oxatis_CategoryId2 INT,
    Oxatis_Oxatis_CategoryId3 INT,
    Oxatis_Oxatis_MetaTitle TEXT,
    Oxatis_Oxatis_MetaDescription TEXT,
    Oxatis_Oxatis_MetaKeywords TEXT,
    Oxatis_Oxatis_Brand VARCHAR(255),
    MainIntervener VARCHAR(255),
    IntrastatNc8NomenclatureId INT,
    Group1 VARCHAR(255),
    Group2 VARCHAR(255),
    NotPrintable BOOLEAN,
    NotIncluded BOOLEAN,
    IsFixedPrice BOOLEAN,
    NonInvoiceableType VARCHAR(255),
    ComponentCalculationType VARCHAR(255),
    ReplacementItem INT,
    WeightUnitId INT,
    NumberOfItemByPackage INT,
    VolumeUnitId INT,
    SupplierId INT,
    EcotaxId INT,
    StockDestination VARCHAR(255),
    StockVarianceAccount VARCHAR(255),
    CurrentStockAccount VARCHAR(255),
    VatId INT,
    sysModuleId INT,
    sysDatabaseId INT,
    sysRecordVersion INT,
    sysRecordVersionId INT,
    sysEditCounter INT,
    LimitDateSafetyDelayMode VARCHAR(255),
    DefaultLifeTime INT,
    PurchasePriceUpdateType VARCHAR(255),
    AnalyticAccounting_GridId INT,
    PurchaseUnitId INT,
    DimensionUnitId INT,
    Oxatis_Oxatis_LongDescription TEXT,
    Oxatis_Oxatis_LongDescriptionClear TEXT,
    Oxatis_Oxatis_SmallImage VARCHAR(255),
    PurchaseBillOfQuantitiesProgram_Program VARCHAR(255),
    CatalogId INT,
    CatalogItemId INT,
    EcotaxFurnitureId INT,
    PurchaseUnitPriceProgram_Program VARCHAR(255),
    LocalizableCaption_2 TEXT,
    LocalizableDesCom_2 TEXT,
    LocalizableDesCom_Clear_2 TEXT,
    LocalizableCaption_3 TEXT,
    LocalizableCaption_4 TEXT,
    LocalizableCaption_5 TEXT,
    LocalizableDesCom_3 TEXT,
    LocalizableDesCom_Clear_3 TEXT,
    LocalizableDesCom_4 TEXT,
    LocalizableDesCom_Clear_4 TEXT,
    LocalizableDesCom_5 TEXT,
    LocalizableDesCom_Clear_5 TEXT,
    IntrastatOriginCountryId INT,
    ParentRangeItemId INT,
    RangeTypeElementId0 INT,
    RangeTypeElementId1 INT,
    RangeTypeElementId2 INT,
    RangeTypeElementId3 INT,
    RangeTypeElementId4 INT,
    DefaultAllowedStorehouseId INT,
    MaintenanceContractTemplateId INT,
    GuaranteeTypeId INT,
    StockBillOfQuantitiesProgram_Program VARCHAR(255),
    PosThumbnail VARCHAR(255),
    GiftVoucherCashValue DECIMAL(10, 2),
    GiftVoucherValidityDuration INT,
    IsExtraFee BOOLEAN,
    TimeUnitId INT,
    TechnicalDesCom TEXT,
    TechnicalDesComClear TEXT,
    LocalizableTechnicalDesCom_2 TEXT,
    LocalizableTechnicalDesCom_Clear_2 TEXT,
    LocalizableTechnicalDesCom_3 TEXT,
    LocalizableTechnicalDesCom_Clear_3 TEXT,
    LocalizableTechnicalDesCom_4 TEXT,
    LocalizableTechnicalDesCom_Clear_4 TEXT,
    LocalizableTechnicalDesCom_5 TEXT,
    LocalizableTechnicalDesCom_Clear_5 TEXT,
    CompetenceId INT,
    EquipmentTypeId INT,
    ScheduleEventTemplateId INT,
    CompetenceNumberToPlan INT,
    EquipmentTypeNumberToPlan INT,
    CadenceDuration INT,
    CadenceDurationType VARCHAR(255),
    CadenceDurationQuantity INT,
    InstallationTime INT,
    LabourCode VARCHAR(255),
    AutoUpdateLabourPrice BOOLEAN,
    IsEquipment BOOLEAN,
    InstallationCalculationType VARCHAR(255),
    MaterialPrices_PurchasePrice DECIMAL(10, 2),
    MaterialPrices_ChargeRate DECIMAL(10, 2),
    MaterialPrices_ChargeAmount DECIMAL(10, 2),
    MaterialPrices_CostPrice DECIMAL(10, 2),
    MaterialPrices_InterestRate DECIMAL(10, 2),
    MaterialPrices_InterestAmount DECIMAL(10, 2),
    MaterialPrices_SalePriceVatExcluded DECIMAL(10, 2),
    MaterialPrices_BrandRate DECIMAL(10, 2),
    MaterialPrices_VatId INT,
    MaterialPrices_VatAmount DECIMAL(10, 2),
    MaterialPrices_SalePriceVatIncluded DECIMAL(10, 2),
    MaterialPrices_AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    MaterialPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    MaterialPrices_IsFixedPrice BOOLEAN,
    MaterialPrices_EcotaxFurnitureId INT,
    LabourPrices_PurchasePrice DECIMAL(10, 2),
    LabourPrices_ChargeRate DECIMAL(10, 2),
    LabourPrices_ChargeAmount DECIMAL(10, 2),
    LabourPrices_CostPrice DECIMAL(10, 2),
    LabourPrices_InterestRate DECIMAL(10, 2),
    LabourPrices_InterestAmount DECIMAL(10, 2),
    LabourPrices_SalePriceVatExcluded DECIMAL(10, 2),
    LabourPrices_BrandRate DECIMAL(10, 2),
    LabourPrices_VatId INT,
    LabourPrices_VatAmount DECIMAL(10, 2),
    LabourPrices_SalePriceVatIncluded DECIMAL(10, 2),
    LabourPrices_AdvisedSalePriceVATExcluded DECIMAL(10, 2),
    LabourPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    LabourPrices_IsFixedPrice BOOLEAN,
    LabourPrices_EcotaxFurnitureId INT,
    CanBePartiallyInvoiced BOOLEAN,
    PickMovementDisallowedOnTotallyBookedItem BOOLEAN,
    SalePriceModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SalePriceModifiedUserId VARCHAR(255),
    TarifeoCode VARCHAR(255),
    TarifeoFullCode VARCHAR(255),
    TarifeoProducerId INT,
    ProducerName VARCHAR(255),
    TarifeoPriceDate DATE,
    TarifeoPriceVersion INT,
    TarifeoUpdateDateTIme TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IsSubscription BOOLEAN,
    SubscriptionPassings INT,
    SubscriptionTotalCostPrice DECIMAL(10, 2),
    SubscriptionTotalPurchasePrice DECIMAL(10, 2),
    SubscriptionTotalSalePriceVatExcluded DECIMAL(10, 2),
    SubscriptionValidityDuration INT
);

-- Version 1
CREATE TABLE IF NOT EXISTS customer (
    CheckExceedCommitmentDate BOOLEAN,
    DueCommitmentsXDay NUMERIC,
    EffectOfTradeAmount NUMERIC,
    GenerateVCS BOOLEAN,
    ThirdLanguage TEXT,
    InvoicingChargesAmount NUMERIC,
    AutomaticStockBooking BOOLEAN,
    CustomerToUseInCustomerProducts NUMERIC,
    ExtendedCurrentAmount NUMERIC,
    ThresholdBeforeExceedAmount NUMERIC,
    Name TEXT,
    UseInvoicingAddressAsDeliveryAddress BOOLEAN,
    UseInvoicingContactAsDeliveryContact BOOLEAN,
    MainDeliveryAddress_Npai BOOLEAN,
    MainInvoicingAddress_Npai BOOLEAN,
    MainDeliveryContact_NaturalPerson BOOLEAN,
    MainDeliveryContact_OptIn BOOLEAN,
    Id TEXT,
    MainInvoicingContact_NaturalPerson BOOLEAN,
    MainInvoicingContact_OptIn BOOLEAN,
    NaturalPerson BOOLEAN,
    TerritorialityId UUID,
    FinancialDiscountType NUMERIC,
    FinancialDiscountRate NUMERIC,
    FinancialDiscountPaymentDelay NUMERIC,
    ActiveState NUMERIC,
    DiscountRate NUMERIC,
    SecondDiscountRate NUMERIC,
    AllowedAmount NUMERIC,
    CurrentAmount NUMERIC,
    InitialAmount NUMERIC,
    ExceedAmount NUMERIC,
    MustRetrieveCommitmentsFromAccounting BOOLEAN,
    PriceWithTaxBased BOOLEAN,
    MustBeReminder BOOLEAN,
    DayNumberToFirstReminder NUMERIC,
    DayNumberToSecondReminder NUMERIC,
    DayNumberToThirdReminder NUMERIC,
    IsCustomerAccount BOOLEAN,
    WebContactSendKind NUMERIC,
    SubjectToRE BOOLEAN,
    UniqueId UUID,
    DisallowOrderAssort BOOLEAN,
    DisallowDeliveryAssort BOOLEAN,
    SendReminderToPayerThird BOOLEAN,
    xx_Envoi_carte_voeux BOOLEAN,
    AssortDeliveryByOrder BOOLEAN,
    CreatePosDeliveryOrderByDefault BOOLEAN,
    LoyaltyOriginReportType NUMERIC,
    LoyaltyOriginReportValue NUMERIC,
    LoyaltyValue NUMERIC,
    LoyaltyCardType TEXT,
    LoyaltyCardId TEXT,
    LoyaltyCardCreationDate TIMESTAMP,
    LoyaltyCardValidityDuration NUMERIC,
    LoyaltyCardExpiryDate TIMESTAMP,
    LoyaltyCardRenewalDate TIMESTAMP,
    sysRecordVersion NUMERIC,
    sysRecordVersionId UUID,
    sysEditCounter NUMERIC,
    SelectedReminderReport TEXT,
    ShippingId TEXT,
    DocumentSerialId TEXT,
    IdentificationType TEXT,
    AnalyticAccounting_GridId TEXT,
    Type NUMERIC,
    Accounts_Account TEXT,
    CurrencyId TEXT,
    Group1 TEXT,
    Group2 TEXT,
    ColleagueId TEXT,
    FirstInvoicingDate TIMESTAMP,
    SettlementModeId TEXT,
    PaymentDate TIMESTAMP,
    PriceListCategoryId TEXT,
    Siren TEXT,
    NAF TEXT,
    FamilyId TEXT,
    SubFamilyId TEXT,
    IntracommunityVATNumber TEXT,
    MainInvoicingContact_ExternalId_GoogleId TEXT,
    MainInvoicingContact_ExternalId_OutlookId TEXT,
    Civility TEXT,
    MainDeliveryContact_ExternalId_GoogleId TEXT,
    MainDeliveryContact_ExternalId_OutlookId TEXT,
    MainInvoicingContact_Civility TEXT,
    MainInvoicingContact_Name TEXT,
    MainInvoicingContact_FirstName TEXT,
    MainInvoicingContact_Phone TEXT,
    MainInvoicingContact_CellPhone TEXT,
    MainInvoicingContact_Fax TEXT,
    MainInvoicingContact_Email TEXT,
    MainInvoicingContact_Function TEXT,
    MainInvoicingContact_Department TEXT,
    MainInvoicingAddress_WebSite TEXT,
    MainInvoicingAddress_Longitude NUMERIC,
    MainInvoicingAddress_Latitude NUMERIC,
    MainDeliveryContact_Civility TEXT,
    MainDeliveryContact_Name TEXT,
    MainDeliveryContact_FirstName TEXT,
    MainDeliveryContact_Phone TEXT,
    MainDeliveryContact_CellPhone TEXT,
    MainDeliveryContact_Fax TEXT,
    MainDeliveryContact_Email TEXT,
    MainDeliveryContact_Function TEXT,
    MainDeliveryContact_Department TEXT,
    MainDeliveryAddress_WebSite TEXT,
    MainDeliveryAddress_Longitude NUMERIC,
    MainDeliveryAddress_Latitude NUMERIC,
    MainInvoicingAddress_Address1 TEXT,
    MainInvoicingAddress_Address2 TEXT,
    MainInvoicingAddress_Address3 TEXT,
    MainInvoicingAddress_Address4 TEXT,
    MainInvoicingAddress_ZipCode TEXT,
    MainInvoicingAddress_City TEXT,
    MainInvoicingAddress_State TEXT,
    MainInvoicingAddress_CountryIsoCode TEXT,
    MainInvoicingAddress_Description TEXT,
    MainInvoicingAddress_Civility TEXT,
    MainInvoicingAddress_ThirdName TEXT,
    MainDeliveryAddress_Address1 TEXT,
    MainDeliveryAddress_Address2 TEXT,
    MainDeliveryAddress_Address3 TEXT,
    MainDeliveryAddress_Address4 TEXT,
    MainDeliveryAddress_ZipCode TEXT,
    MainDeliveryAddress_City TEXT,
    MainDeliveryAddress_State TEXT,
    MainDeliveryAddress_CountryIsoCode TEXT,
    MainDeliveryAddress_Description TEXT,
    MainDeliveryAddress_Civility TEXT,
    MainDeliveryAddress_ThirdName TEXT,
    sysCreatedDate TIMESTAMP,
    sysCreatedUser TEXT,
    sysModifiedDate TIMESTAMP,
    sysModifiedUser TEXT,
    NotesClear TEXT,
    Notes TEXT,
    Accounts_BillOfExchangeAccountingAccount TEXT,
    TaxIds0 TEXT,
    TaxIds1 TEXT,
    TaxIds2 TEXT,
    PaymentThirdId TEXT,
    InvoicingThirdId TEXT,
    InvoicingChargesVatId UUID,
    LastInvoicingDate TIMESTAMP,
    DocumentPrintMention TEXT,
    StorehouseId TEXT,
    Accounts_AuxiliaryAccount TEXT,
    Accounts_DoubtfulAccount TEXT,
    SchedulerColor TEXT,
    TravelExpenseId TEXT,
    Accounts_SecurityBondAccount TEXT,
    Accounts_SecurityBondForGoodCompletedWorkAccount TEXT,
    ShowTechnicalSheetOnFront BOOLEAN,
    TechnicalSheetClear TEXT,
    TechnicalSheet TEXT,
    MainDeliveryContact_AllowUsePersonnalDatas BOOLEAN,
    MainInvoicingContact_AllowUsePersonnalDatas BOOLEAN,
    AllowUsePersonnalDatas BOOLEAN,
    Nic TEXT,
    LoyaltyCumulativeTurnoverReport NUMERIC,
    LoyaltyCumulativeTurnover NUMERIC,
    DepositPercentage NUMERIC,
    SecurityBondRate NUMERIC,
    SecurityBondRateForGoodCompletedWork NUMERIC,
    BuyerReference TEXT,
    GoCardLessThirdId TEXT,
    DefaultBankAccountId TEXT
);

CREATE TABLE IF NOT EXISTS item (
    BarCodePrice NUMERIC,
    BarCodeWeight NUMERIC,
    PosAddItem BOOLEAN,
    LoyaltyPoints NUMERIC,
    CalculateLoyaltyFrom NUMERIC,
    GiftVoucher BOOLEAN,
    IntrastatExcluded BOOLEAN,
    CreateCustomerProductInCustomerPark BOOLEAN,
    IsMaintenanceContract BOOLEAN,
    IsGuaranteeExtension BOOLEAN,
    CustomerParkCreation NUMERIC,
    StockBookingAllowed BOOLEAN,
    AutomaticStockBooking BOOLEAN,
    IncludeToRecursiveReplenishment BOOLEAN,
    IncludeToFabricationReplenishment BOOLEAN,
    IncludeToSupplierReplenishment BOOLEAN,
    CadenceQuantity NUMERIC,
    CadenceNumberOfDays NUMERIC,
    DoNotAssortAssemblyRequestsWithDifferentDates BOOLEAN,
    MaximumGapDayToAssort NUMERIC,
    NomenclatureAccountingTransferTypeForSale NUMERIC,
    NomenclatureAccountingTransferTypeForPurchase NUMERIC,
    VirtualPump NUMERIC,
    VirtualStockValue NUMERIC,
    BookedQuantity NUMERIC,
    PurchaseBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    NotOnMarket BOOLEAN,
    PurchaseUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    CanBePartiallyDelivered BOOLEAN,
    Caption TEXT,
    Oxatis_Oxatis_HandlingSurcharge1ST NUMERIC,
    Oxatis_Oxatis_HandlingSurchargeOthers NUMERIC,
    InterventionDurationEqualsQuantity BOOLEAN,
    Height NUMERIC,
    Width NUMERIC,
    Length NUMERIC,
    Oxatis_Oxatis_UseSubFamilyAsBrand BOOLEAN,
    IsManagedByCounterMark BOOLEAN,
    IsCounterMarkForced BOOLEAN,
    SalePurchaseConversionRate NUMERIC,
    LimitDateMode NUMERIC,
    LimitDateSafetyDelay NUMERIC,
    UniqueId UUID,
    PurchasePrice NUMERIC,
    ChargeRate NUMERIC,
    ChargeAmount NUMERIC,
    CostPrice NUMERIC,
    InterestRate NUMERIC,
    InterestAmount NUMERIC,
    SalePriceVatExcluded NUMERIC,
    BrandRate NUMERIC,
    VatAmount NUMERIC,
    SalePriceVatIncluded NUMERIC,
    ManageStock BOOLEAN,
    RealStock NUMERIC,
    Pump NUMERIC,
    StockValue NUMERIC,
    OrderedQuantity NUMERIC,
    SuppliersOrderedQuantity NUMERIC,
    VirtualStock NUMERIC,
    DefaultQuantity NUMERIC,
    Volume NUMERIC,
    Weight NUMERIC,
    NetWeight NUMERIC,
    ComponentsPurchasePrice NUMERIC,
    ComponentsCostPrice NUMERIC,
    ComponentsSalePriceVatExcluded NUMERIC,
    ComponentsSalePriceVatIncluded NUMERIC,
    PrintComponentDetail NUMERIC,
    AssemblingVirtualQuantity NUMERIC,
    DisassemblingQuantity NUMERIC,
    QuantityUsedToAssemblate NUMERIC,
    QuantityFromDisassembling NUMERIC,
    AllowNegativeStock BOOLEAN,
    UseComponentVat BOOLEAN,
    ApplyPriceListOnComponents BOOLEAN,
    ActiveState NUMERIC,
    AdvisedSalePriceVATExcluded NUMERIC,
    SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    TrackingMode NUMERIC,
    AllowComponentsModification BOOLEAN,
    AllowPublishOnWeb BOOLEAN,
    ImageVersion NUMERIC,
    PriceDecimalNumber NUMERIC,
    IsHumanServicesIncludedInAttestation BOOLEAN,
    Oxatis_Oxatis_ShowInStockNote BOOLEAN,
    Oxatis_Oxatis_ShowStockLevel BOOLEAN,
    Oxatis_Oxatis_ShowIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStock BOOLEAN,
    Oxatis_Oxatis_SaleIfOutOfStockScenario NUMERIC,
    Oxatis_Oxatis_ShowDaysToship BOOLEAN,
    Oxatis_Oxatis_ShipPrice NUMERIC,
    Oxatis_Oxatis_DaysToship NUMERIC,
    Oxatis_Oxatis_UserMainSupplierDaysToship BOOLEAN,
    Id TEXT,
    ItemType NUMERIC,
    BillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    SaleUnitPriceProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    UpdateComponentsStockInFabrication BOOLEAN,
    CustomersDeliveryOrderPreparingQuantity NUMERIC,
    CustomersReturnOrderPreparingQuantity NUMERIC,
    SuppliersDeliveryOrderPreparingQuantity NUMERIC,
    SuppliersReturnOrderPreparingQuantity NUMERIC,
    StockBillOfQuantitiesProgram_KeepActiveFromQuoteToOrder BOOLEAN,
    PurchaseChargesRate NUMERIC,
    PosIsScale BOOLEAN,
    PosTare NUMERIC,
    BillOfQuantitiesProgram_Program TEXT,
    ReplenishmentDeliveryAddressType NUMERIC,
    SaleUnitPriceProgram_Program TEXT,
    DesCom TEXT,
    DesComClear TEXT,
    ItemImage TEXT,
    BarCode TEXT,
    UnitId TEXT,
    FamilyId TEXT,
    SubFamilyId TEXT,
    sysCreatedDate TIMESTAMP,
    sysCreatedUser TEXT,
    sysModifiedDate TIMESTAMP,
    sysModifiedUser TEXT,
    NotesClear TEXT,
    Notes TEXT,
    Oxatis_Oxatis_CategoryType1 TEXT,
    Oxatis_Oxatis_CategoryType2 TEXT,
    Oxatis_Oxatis_CategoryType3 TEXT,
    Oxatis_Oxatis_CategoryId1 TEXT,
    Oxatis_Oxatis_CategoryId2 TEXT,
    Oxatis_Oxatis_CategoryId3 TEXT,
    Oxatis_Oxatis_MetaTitle TEXT,
    Oxatis_Oxatis_MetaDescription TEXT,
    Oxatis_Oxatis_MetaKeywords TEXT,
    Oxatis_Oxatis_Brand TEXT,
    MainIntervener TEXT,
    IntrastatNc8NomenclatureId TEXT,
    Group1 TEXT,
    Group2 TEXT,
    NotPrintable TEXT,
    NotIncluded TEXT,
    IsFixedPrice TEXT,
    NonInvoiceableType TEXT,
    ComponentCalculationType TEXT,
    ReplacementItem TEXT,
    WeightUnitId TEXT,
    NumberOfItemByPackage NUMERIC,
    VolumeUnitId TEXT,
    SupplierId TEXT,
    EcotaxId TEXT,
    StockDestination NUMERIC,
    StockVarianceAccount TEXT,
    CurrentStockAccount TEXT,
    VatId UUID,
    sysRecordVersion NUMERIC,
    sysRecordVersionId UUID,
    sysEditCounter NUMERIC,
    LimitDateSafetyDelayMode TEXT,
    DefaultLifeTime TEXT,
    PurchasePriceUpdateType TEXT,
    AnalyticAccounting_GridId TEXT,
    PurchaseUnitId TEXT,
    DimensionUnitId TEXT,
    Oxatis_Oxatis_LongDescription TEXT,
    Oxatis_Oxatis_LongDescriptionClear TEXT,
    Oxatis_Oxatis_SmallImage TEXT,
    PurchaseBillOfQuantitiesProgram_Program TEXT,
    CatalogId TEXT,
    CatalogItemId TEXT,
    EcotaxFurnitureId TEXT,
    PurchaseUnitPriceProgram_Program TEXT,
    LocalizableCaption_2 TEXT,
    LocalizableDesCom_2 TEXT,
    LocalizableDesCom_Clear_2 TEXT,
    LocalizableCaption_3 TEXT,
    LocalizableCaption_4 TEXT,
    LocalizableCaption_5 TEXT,
    LocalizableDesCom_3 TEXT,
    LocalizableDesCom_Clear_3 TEXT,
    LocalizableDesCom_4 TEXT,
    LocalizableDesCom_Clear_4 TEXT,
    LocalizableDesCom_5 TEXT,
    LocalizableDesCom_Clear_5 TEXT,
    IntrastatOriginCountryId TEXT,
    ParentRangeItemId TEXT,
    RangeTypeElementId0 TEXT,
    RangeTypeElementId1 TEXT,
    RangeTypeElementId2 TEXT,
    RangeTypeElementId3 TEXT,
    RangeTypeElementId4 TEXT,
    DefaultAllowedStorehouseId TEXT,
    MaintenanceContractTemplateId TEXT,
    GuaranteeTypeId TEXT,
    StockBillOfQuantitiesProgram_Program TEXT,
    PosThumbnail TEXT,
    GiftVoucherCashValue NUMERIC,
    GiftVoucherValidityDuration NUMERIC,
    IsExtraFee BOOLEAN,
    TimeUnitId TEXT,
    TechnicalDesCom TEXT,
    TechnicalDesComClear TEXT,
    LocalizableTechnicalDesCom_2 TEXT,
    LocalizableTechnicalDesCom_Clear_2 TEXT,
    LocalizableTechnicalDesCom_3 TEXT,
    LocalizableTechnicalDesCom_Clear_3 TEXT,
    LocalizableTechnicalDesCom_4 TEXT,
    LocalizableTechnicalDesCom_Clear_4 TEXT,
    LocalizableTechnicalDesCom_5 TEXT,
    LocalizableTechnicalDesCom_Clear_5 TEXT,
    CompetenceId TEXT,
    EquipmentTypeId TEXT,
    ScheduleEventTemplateId TEXT,
    CompetenceNumberToPlan NUMERIC,
    EquipmentTypeNumberToPlan NUMERIC,
    CadenceDuration NUMERIC,
    CadenceDurationType NUMERIC,
    CadenceDurationQuantity NUMERIC,
    InstallationTime NUMERIC,
    LabourCode TEXT,
    AutoUpdateLabourPrice BOOLEAN,
    IsEquipment BOOLEAN,
    InstallationCalculationType NUMERIC,
    MaterialPrices_PurchasePrice NUMERIC,
    MaterialPrices_ChargeRate NUMERIC,
    MaterialPrices_ChargeAmount NUMERIC,
    MaterialPrices_CostPrice NUMERIC,
    MaterialPrices_InterestRate NUMERIC,
    MaterialPrices_InterestAmount NUMERIC,
    MaterialPrices_SalePriceVatExcluded NUMERIC,
    MaterialPrices_BrandRate NUMERIC,
    MaterialPrices_VatId UUID,
    MaterialPrices_VatAmount NUMERIC,
    MaterialPrices_SalePriceVatIncluded NUMERIC,
    MaterialPrices_AdvisedSalePriceVATExcluded NUMERIC,
    MaterialPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    MaterialPrices_IsFixedPrice TEXT,
    MaterialPrices_EcotaxFurnitureId TEXT,
    LabourPrices_PurchasePrice NUMERIC,
    LabourPrices_ChargeRate NUMERIC,
    LabourPrices_ChargeAmount NUMERIC,
    LabourPrices_CostPrice NUMERIC,
    LabourPrices_InterestRate NUMERIC,
    LabourPrices_InterestAmount NUMERIC,
    LabourPrices_SalePriceVatExcluded NUMERIC,
    LabourPrices_BrandRate NUMERIC,
    LabourPrices_VatId UUID,
    LabourPrices_VatAmount NUMERIC,
    LabourPrices_SalePriceVatIncluded NUMERIC,
    LabourPrices_AdvisedSalePriceVATExcluded NUMERIC,
    LabourPrices_SetItemSalePriceWithAdvisedSalePrice BOOLEAN,
    LabourPrices_IsFixedPrice TEXT,
    LabourPrices_EcotaxFurnitureId TEXT,
    CanBePartiallyInvoiced BOOLEAN,
    PickMovementDisallowedOnTotallyBookedItem BOOLEAN,
    SalePriceModifiedDate TIMESTAMP,
    SalePriceModifiedUserId TEXT,
    TarifeoCode TEXT,
    TarifeoFullCode TEXT,
    TarifeoProducerId TEXT,
    ProducerName TEXT,
    TarifeoPriceDate TIMESTAMP,
    TarifeoPriceVersion TEXT,
    TarifeoUpdateDateTIme TIMESTAMP,
    IsSubscription BOOLEAN,
    SubscriptionPassings NUMERIC,
    SubscriptionTotalCostPrice NUMERIC,
    SubscriptionTotalPurchasePrice NUMERIC,
    SubscriptionTotalSalePriceVatExcluded NUMERIC,
    SubscriptionValidityDuration NUMERIC
);

